[package]
name = "yma-migration"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "数据库迁移管理，支持SQL迁移文件加载、版本追踪、回滚"

[dependencies]
tokio = { version = "1.52.1", features = ["rt-multi-thread", "fs"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.38", features = ["serde"] }
sqlx = { workspace = true }
dashmap = "6"