[package]
name = "yma-config"
version.workspace = true
edition.workspace = true
description = "配置管理统一库"

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
parking_lot.workspace = true
once_cell.workspace = true
toml = "0.8"

[dev-dependencies]
serde_json.workspace = true